# Generated by Django 6.0.1 on 2026-02-01 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresarios", "0004_alter_empresas_estagio_duediligence"),
        ("investidores", "0002_kyc"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoDigital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("MUTUO", "Mútuo Conversível"),
                            ("NDA", "Termo de Confidencialidade (NDA)"),
                            ("SAFE", "SAFE (Simple Agreement for Future Equity)"),
                            ("INVESTIMENTO", "Contrato de Investimento"),
                            ("OUTRO", "Outro"),
                        ],
                        default="MUTUO",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("PENDING", "Pendente de Envio"),
                            ("SENT", "Enviado para Assinatura"),
                            ("PARTIAL", "Parcialmente Assinado"),
                            ("SIGNED", "Totalmente Assinado"),
                            ("REJECTED", "Rejeitado"),
                            ("EXPIRED", "Expirado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "documento_id_externo",
                    models.CharField(
                        blank=True,
                        help_text="ID do documento na plataforma de assinatura",
                        max_length=100,
                    ),
                ),
                ("url_assinatura_investidor", models.URLField(blank=True)),
                ("url_assinatura_empresario", models.URLField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                ("assinado_investidor_em", models.DateTimeField(blank=True, null=True)),
                ("assinado_empresario_em", models.DateTimeField(blank=True, null=True)),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
                ("expira_em", models.DateTimeField(blank=True, null=True)),
                (
                    "documento_assinado",
                    models.FileField(
                        blank=True, null=True, upload_to="contratos_assinados/"
                    ),
                ),
                ("hash_documento", models.CharField(blank=True, max_length=64)),
                (
                    "proposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="investidores.propostainvestimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato Digital",
                "verbose_name_plural": "Contratos Digitais",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoDataRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("arquivo", models.FileField(upload_to="dataroom/")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DRE", "Demonstração de Resultados (DRE)"),
                            ("BP", "Balanço Patrimonial"),
                            ("FC", "Fluxo de Caixa"),
                            ("PLANILHA", "Planilha Financeira"),
                            ("CONTRATO", "Contrato Social/Estatuto"),
                            ("PATENTE", "Patente/Propriedade Intelectual"),
                            ("AUDITORIA", "Relatório de Auditoria"),
                            ("OUTRO", "Outro Documento"),
                        ],
                        default="OUTRO",
                        max_length=20,
                    ),
                ),
                (
                    "privado",
                    models.BooleanField(
                        default=True,
                        help_text="Se True, apenas investidores com Match podem visualizar",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_dataroom",
                        to="empresarios.empresas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Data Room",
                "verbose_name_plural": "Documentos Data Room",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="AcessoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_acesso", models.DateTimeField(auto_now_add=True)),
                ("ip_acesso", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "investidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acessos",
                        to="investidores.documentodataroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_acesso"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("processado", models.BooleanField(default=False)),
                ("erro", models.TextField(blank=True)),
                ("recebido_em", models.DateTimeField(auto_now_add=True)),
                ("processado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_logs",
                        to="investidores.contratodigital",
                    ),
                ),
            ],
            options={
                "ordering": ["-recebido_em"],
            },
        ),
    ]
