# Generated by Django 5.1.1 on 2026-07-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investidores', '0003_contratodigital_documentodataroom_acessodocumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostainvestimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
