# Generated by Django 5.1.1 on 2026-07-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investidores', '0004_alter_propostainvestimento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostainvestimento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
