# Generated by Django 5.1.1 on 2026-01-28 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresarios", "0003_metricas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresas",
            name="estagio",
            field=models.CharField(
                choices=[
                    ("I", "Tenho apenas uma ideia"),
                    ("MVP", "Possuo um MVP"),
                    ("MVPP", "Possuo um MVP com clientes pagantes"),
                    ("E", "Empresa pronta para escalar"),
                ],
                default="I",
                max_length=4,
            ),
        ),
        migrations.CreateModel(
            name="DueDiligence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_analise", models.DateField(auto_now_add=True)),
                ("status_compliance", models.BooleanField(default=False)),
                ("score_risco", models.IntegerField(default=0)),
                ("analise_detalhada", models.TextField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresarios.empresas",
                    ),
                ),
            ],
        ),
    ]
