# Generated by Django 5.1.1 on 2026-02-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresarios", "0004_alter_empresas_estagio_duediligence"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresas",
            name="taxa_intermediacao",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Taxa de Intermediação",
            ),
        ),
        migrations.AddField(
            model_name="empresas",
            name="valor_liquido",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Valor Líquido"
            ),
        ),
    ]
