# Generated by Django 5.1.1 on 2026-07-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0005_empresas_taxa_intermediacao_empresas_valor_liquido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='taxa_intermediacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Taxa de Intermediação'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Líquido'),
        ),
    ]
