# Generated by Django 6.0.4 on 2026-04-16 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=50)),
                ('base_asset', models.CharField(max_length=10)),
                ('quote_asset', models.CharField(default='BRL', max_length=10)),
                ('side', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda')], max_length=4)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_base', models.DecimalField(decimal_places=8, help_text='Market price without spread', max_digits=20)),
                ('spread_applied', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_final', models.DecimalField(decimal_places=8, help_text='Price shown to client', max_digits=20)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceita'), ('E', 'Expirada'), ('C', 'Cancelada')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_slug', models.SlugField(help_text='Unique ID for URL/Subdomain', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='otc/logos/')),
                ('primary_color', models.CharField(default='#000000', help_text='Hex color', max_length=7)),
                ('default_spread_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otc_desk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=50)),
                ('final_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total_volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('total_quote', models.DecimalField(decimal_places=8, help_text='Total in BRL/USD', max_digits=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='otc.quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
